### ISSUE TITLE
plot3d is not working with the latest kernel

### ISSUE THREAD

**Issue by ahmedabdelkawy** [pyiron/structuretoolkit#142]
Plot3d() - nglview mode - has not been working for a while now. 

output:
Error displaying widget: model not found

code to reproduce:
```
pr = Project('plot3d')
al_struc = pr.create.structure.bulk('Al', cubic=True)
al_struc.plot3d()
```

directly from nglview

```
import nglview
from structuretoolkit.visualize import _plot3d, _ngl_write_structure
pr = Project('plot3d')
al_struc = pr.create.structure.bulk('Al', cubic=True)
structure = al_struc.copy()
elements = structure.get_chemical_symbols()
atomic_numbers = structure.get_atomic_numbers()
positions = structure.positions
struct = nglview.TextStructure(_ngl_write_structure(elements, positions, structure.cell))
view = nglview.NGLWidget(struct)
view
```

Things I tried and did not work: 
1.using latest structuretoolkit (0.0.21) and atomistics (0.4.14) and the ones currently on the cluster structuretoolkit (0.0.18) and atomistics (0.4.9).
2.downgrading nglview

Things I tried and worked:
changing the kernel from pyiron/latest to python 3

**Comment by ahmedabdelkawy** [comment]
@niklassiemer

**Comment by niklassiemer** [comment]
I downgraded (luckily only) nglview to 0.3.8 which is in sync with the widgets javascript installed in the old jupyterhub installation.

Background:
On cmti001 the JupyterHUB and the SingleUserServer the former one spawns for each of us is running on the old pyiron/dev environment which cannot be updated any longer. This one. thus, has a fixed version of the javascript used to display the widgets in the browser. Now, after ipywidgets also nglview changed its internal API to communicate the widget state from python to the javascript on the JupyterHUB. This broke the functionality.

On cmti002 the jupyterhub and the singleuser-server are spawned from individual environments (jhub and pyiron/latest, respectively). I.e. no legacy env around.

**Comment by ahmedabdelkawy** [comment]
3.0.8* Just to avoid confusion in the future

Thank you very much, Niklas, for the quick fix and the explanation. I confirm that that issue is now fixed. On the other hand, is there a better place to report the cluster/enviornment related issues (which are more internal) or the repo of the underlying code is already okay?

**Comment by niklassiemer** [comment]
Good question, we have the onboarding repo on gitlab. And we have the infrastructure team, but there is no really good place to report this... _Tagging_ me here like you did pulls at least my attention :)
